### ISSUE TITLE
Top text doesn't load correctly on mobile in portrait mode

### ISSUE THREAD

**Issue by youngchief-btw** [Team-Donut/TeamDonut.tk#3] opened 2020-04-04 01:30 UTC
The text "A group of teens who make web apps, Glitch projects and userscripts, for users and developers alike." at the top of the page get cropped on a phone in portrait mode

I think it has to do with CSS?

**Comment by khalby786** [comment] 2020-04-04 07:26
Thanks for reporting, will be fixed soon!

**Comment by khalby786** [comment] 2020-04-04 07:53
This is subject to change, as we might be changing our site to Gatsby.

**Comment by Nelson-Chinedu** [comment] 2020-04-04 08:26
Hey @khalby786, let me be of help if the issue is open

**Comment by khalby786** [comment] 2020-04-04 08:38
Thanks @Nelson-Chinedu! Feel free to take a look and let me know where it is wrong, although access to edit the repo lies only with the members of DonutSquad!

**Comment by khalby786** [comment] 2020-04-04 08:48
@youngchief-btw can I have a snapshot of what it looks like on mobile?

**Comment by khalby786** [comment] 2020-04-04 09:18
@Nelson-Chinedu @youngchief-btw This issue is no longer relevant and will be closed because our new site made using Gatsby will be deployed soon!

**Closed as completed by khalby786** 2020-04-04 09:18 UTC
Labels: bug, good first issue
